// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx0mUngQdsy7gQohWI4SMNxGv4IxTHJgA',
    appId: '1:409243425684:web:f450ca86cd0c3a4d28cd81',
    messagingSenderId: '409243425684',
    projectId: 'my-chatting-app-4ea1e',
    authDomain: 'my-chatting-app-4ea1e.firebaseapp.com',
    storageBucket: 'my-chatting-app-4ea1e.appspot.com',
    measurementId: 'G-GQCDYHRDCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDecVBKWBV5sDpWJHOoCJQSnE5uxHi_GxY',
    appId: '1:409243425684:android:a40c15a516d65b5828cd81',
    messagingSenderId: '409243425684',
    projectId: 'my-chatting-app-4ea1e',
    storageBucket: 'my-chatting-app-4ea1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0hzcwXh_kZcT8icoGY5iJE1EwOazEIIE',
    appId: '1:409243425684:ios:32ca4cc4b200117428cd81',
    messagingSenderId: '409243425684',
    projectId: 'my-chatting-app-4ea1e',
    storageBucket: 'my-chatting-app-4ea1e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0hzcwXh_kZcT8icoGY5iJE1EwOazEIIE',
    appId: '1:409243425684:ios:1149b66381258e4528cd81',
    messagingSenderId: '409243425684',
    projectId: 'my-chatting-app-4ea1e',
    storageBucket: 'my-chatting-app-4ea1e.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
